#!/usr/bin/env python3
"""
Generate the Xplorer parameter disposition document from firmware source.

    python Tools/xplorer/gen_param_docs.py              # write all outputs
    python Tools/xplorer/gen_param_docs.py --check      # CI: fail on drift
    python Tools/xplorer/gen_param_docs.py --format html

Everything in the output is derived from source. Do not hand-edit the outputs -
edit the inputs and regenerate.

INPUTS (all in-repo)
  hwdef defaults.parm ......... default value + @READONLY  (the disposition truth)
  GCS_Param_Clamps.h .......... enforced Range min/max
  var_info tables ............. AP_PARAM_FLAG_HIDDEN -> user_visible
  Lua applet PARAM_TABLEs ..... script-defined params (no @Param metadata)
  apm.pdef.json ............... display name / description / units / values,
                                generated by Tools/autotest/param_metadata
  param_manifest.txt .......... authoritative row set (see that file's header)
  param_notes.csv ............. HUMAN-AUTHORED notes, the one hand-edited input

OUTPUTS (doc/params/)
  xplorer-params.csv / .xlsx / .html
"""

import argparse
import csv
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))

BOARD = 'CubeOrangePlus-ODID'
VEHICLE = 'ArduCopter'

DEFAULTS_PARM = os.path.join(REPO, 'libraries/AP_HAL_ChibiOS/hwdef', BOARD, 'defaults.parm')
CLAMPS_H = os.path.join(REPO, 'libraries/GCS_MAVLink/GCS_Param_Clamps.h')
PDEF_JSON = os.path.join(REPO, 'apm.pdef.json')
MANIFEST = os.path.join(HERE, 'param_manifest.txt')
NOTES = os.path.join(HERE, 'param_notes.csv')
OVERRIDES = os.path.join(HERE, 'param_meta_overrides.json')
WAIVERS = os.path.join(HERE, 'param_check_waivers.csv')
OUTDIR = os.path.join(REPO, 'doc', 'params')

# Files that may carry AP_PARAM_FLAG_HIDDEN, mapped to the parameter-name prefix
# their var_info table sits under. If a HIDDEN marker turns up in a file that is
# not listed here the run FAILS - that is deliberate, it is the tripwire that
# stops the doc silently going stale when hiding is added somewhere new.
HIDDEN_SOURCES = {
    'ArduCopter/Parameters.cpp': '',
    'libraries/RC_Channel/RC_Channels_VarInfo.h': 'RC',
    'libraries/SRV_Channel/SRV_Channels.cpp': 'SERVO',
}
# HIDDEN markers that are upstream ArduPilot, in groups already hidden wholesale
# or not compiled for this board. Listed so the tripwire stays quiet about them.
HIDDEN_IGNORE = {
    'libraries/AP_ICEngine/AP_ICEngine.cpp',      # ICE_FMT_VER, ICE not enabled
    'libraries/AP_OSD/AP_OSD_Screen.cpp',         # OSD group hidden wholesale
}

# Lua applets whose param:add_table entries should appear in the doc, as
# (tracked path, param prefix). Use the libraries/AP_Scripting/applets copy:
# ArduCopter/scripts/ is gitignored (.gitignore:147), so it is absent on a fresh
# clone. LUA_DEPLOY_MIRROR is the untracked working copy that gets deployed to
# the SD card; if it exists and differs, the run warns rather than silently
# documenting a different script than the one that flies.
LUA_APPLETS = [
    ('libraries/AP_Scripting/applets/copter-fly-figure-8-v2.lua', 'PTRN'),
]
# defaults.parm copies that must stay byte-identical to DEFAULTS_PARM.
# CubeOrangePlus-ODID-DEV needs its own copy because chibios_hwdef.py only looks
# in the board's own directory, not through the include chain; the DEV unlock is
# done at runtime by name, so the files never need to differ.
DEFAULTS_MIRRORS = [
    'libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus/defaults.parm',
    'libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus-ODID-DEV/defaults.parm',
]
DEV_UNLOCK_H = 'libraries/AP_Param/xplorer_dev_unlock.h'

LUA_DEPLOY_MIRROR = {
    'libraries/AP_Scripting/applets/copter-fly-figure-8-v2.lua':
        'ArduCopter/scripts/copter-fly-figure-8-v2.lua',
}


def warn(msg):
    print('  ! %s' % msg, file=sys.stderr)


# --------------------------------------------------------------------------
# inputs
# --------------------------------------------------------------------------

def git(*args):
    try:
        return subprocess.check_output(['git', '-C', REPO] + list(args),
                                       text=True, stderr=subprocess.DEVNULL).strip()
    except Exception:
        return ''


def parse_defaults_parm(path):
    """-> {name: (value, readonly, inline_comment)}"""
    out = {}
    for raw in open(path, encoding='utf-8'):
        s = raw.strip()
        if not s or s.startswith('#'):
            continue
        comment = ''
        if '#' in s:
            s, comment = s.split('#', 1)
            comment, s = comment.strip(), s.strip()
        readonly = '@READONLY' in s
        parts = s.replace('@READONLY', '').split()
        if len(parts) < 2:
            warn('unparsed defaults.parm line: %s' % raw.rstrip())
            continue
        try:
            out[parts[0]] = (float(parts[1]), readonly, comment)
        except ValueError:
            warn('unparsed value in defaults.parm: %s' % raw.rstrip())
    return out


def parse_clamps(path):
    src = open(path, encoding='utf-8').read()
    body = src.split('xplorer_param_clamps[]', 1)[-1]
    return {m.group(1): (float(m.group(2)), float(m.group(3)))
            for m in re.finditer(
                r'\{\s*"([A-Z0-9_]+)"\s*,\s*(-?[\d.]+)f\s*,\s*(-?[\d.]+)f\s*\}', body)}


def derive_hidden():
    """Scan the source for AP_PARAM_FLAG_HIDDEN. Returns (prefixes, exact_names).

    Fails loudly if a HIDDEN marker appears in an unregistered file.
    """
    prefixes, exact = [], set()

    found_files = set()
    for root, dirs, files in os.walk(REPO):
        dirs[:] = [d for d in dirs
                   if d not in ('.git', 'build', 'modules', '__pycache__')]
        for fn in files:
            if not fn.endswith(('.cpp', '.h')):
                continue
            p = os.path.join(root, fn)
            rel = os.path.relpath(p, REPO).replace('\\', '/')
            if rel.startswith('libraries/AP_Param/AP_Param'):
                continue          # the macro definitions themselves
            try:
                src = open(p, encoding='utf-8', errors='ignore').read()
            except OSError:
                continue
            if 'AP_PARAM_FLAG_HIDDEN' not in src and '_HIDDEN(' not in src:
                continue
            if re.search(r'^\s*#\s*define\s+\w*_HIDDEN', src, re.M) and \
               'AP_PARAM_FLAG_HIDDEN' not in src:
                continue
            found_files.add(rel)

    unknown = found_files - set(HIDDEN_SOURCES) - HIDDEN_IGNORE
    if unknown:
        raise SystemExit(
            'FAIL: AP_PARAM_FLAG_HIDDEN found in unregistered file(s):\n  ' +
            '\n  '.join(sorted(unknown)) +
            '\n\nAdd each to HIDDEN_SOURCES (with the prefix its var_info sits '
            'under) or HIDDEN_IGNORE in %s, then re-run.' % os.path.basename(__file__))

    for rel, base in HIDDEN_SOURCES.items():
        path = os.path.join(REPO, rel)
        if not os.path.exists(path):
            raise SystemExit('FAIL: HIDDEN_SOURCES lists a missing file: %s' % rel)
        src = open(path, encoding='utf-8', errors='ignore').read()
        src = re.sub(r'^\s*#\s*define.*$', '', src, flags=re.M)

        # whole-group hiding: GOBJECT_HIDDEN(var, "PREFIX", Class)
        for m in re.finditer(r'\b(?:GOBJECT|GOBJECTPTR|GGROUP|GOBJECTN|'
                             r'GOBJECTVARPTR)_HIDDEN\s*\(\s*[^,]+,\s*"([^"]*)"', src):
            prefixes.append(base + m.group(1))
        # nested subgroup: AP_SUBGROUPINFO_HIDDEN(elem, "PREFIX", ...)
        for m in re.finditer(r'\bAP_SUBGROUPINFO_HIDDEN\s*\(\s*[^,]+,\s*"([^"]*)"', src):
            prefixes.append(base + m.group(1))
        # single scalar: GSCALAR_HIDDEN(var, "NAME", def)
        for m in re.finditer(r'\bGSCALAR_HIDDEN\s*\(\s*[^,]+,\s*"([^"]*)"', src):
            exact.add(base + m.group(1))
        # single group param carrying the flag
        for m in re.finditer(r'\bAP_GROUPINFO_FLAGS(?:_FRAME)?\s*\(\s*"([^"]*)"'
                             r'(?:[^;]*?)AP_PARAM_FLAG_HIDDEN', src):
            exact.add(base + m.group(1))

    return sorted(set(prefixes), key=len, reverse=True), exact


def parse_lua_params(rel, prefix):
    """Pull a Lua applet's param:add_table entries and inline comments."""
    path = os.path.join(REPO, rel)
    if not os.path.exists(path):
        warn('Lua applet not found: %s' % rel)
        return {}
    src = open(path, encoding='utf-8', errors='ignore').read()
    m = re.search(r'PARAM_TABLE\s*=\s*\{(.*?)\n\}', src, re.S)
    if not m:
        warn('no PARAM_TABLE found in %s' % rel)
        return {}
    out = {}
    for line in m.group(1).split('\n'):
        e = re.match(r"\s*\{\s*'([A-Z0-9_]+)'\s*,\s*(-?[\d.]+)\s*\}\s*,?\s*(?:--\s*\d*:?\s*(.*))?",
                     line)
        if not e:
            continue
        name = '%s_%s' % (prefix, e.group(1))
        out[name] = {
            'default': float(e.group(2)),
            'description': (e.group(3) or '').strip(),
            'source': 'Lua applet: %s' % rel,
        }
    # Script-side clamps. In the source the name is built with a format string,
    # so the literal text is "%s_NAME", not "<PREFIX>_NAME".
    for e in re.finditer(r"clamp\(\s*(?:math\.floor\(\s*)?param_get\(\s*\(\s*'%s?s?_?([A-Z0-9_]+)'"
                         r".*?,\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*\)", src):
        n = '%s_%s' % (prefix, e.group(1))
        if n in out:
            out[n]['range'] = (float(e.group(2)), float(e.group(3)))
    return out


def ensure_pdef(force=False):
    """Generate apm.pdef.json if absent or older than the newest source file."""
    script = os.path.join(REPO, 'Tools/autotest/param_metadata/param_parse.py')
    if os.path.exists(PDEF_JSON) and not force:
        return
    print('  generating apm.pdef.json (%s) ...' % VEHICLE)
    subprocess.check_call([sys.executable, script, '--vehicle', VEHICLE,
                           '--format', 'json'], cwd=REPO,
                          stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if not os.path.exists(PDEF_JSON):
        raise SystemExit('FAIL: param_parse.py did not produce %s' % PDEF_JSON)


def load_pdef():
    d = json.load(open(PDEF_JSON, encoding='utf-8'))
    meta = {}
    for _, params in d.items():
        if not isinstance(params, dict):
            continue
        for name, m in params.items():
            if isinstance(m, dict):
                meta.setdefault(name, m)
    # Hand-written metadata for params the upstream generator cannot parse.
    if os.path.exists(OVERRIDES):
        ov = json.load(open(OVERRIDES, encoding='utf-8'))
        for name, m in ov.items():
            if name.startswith('_'):
                continue
            if name in meta:
                warn('override for %s is now redundant - upstream parses it, '
                     'consider removing it from %s'
                     % (name, os.path.basename(OVERRIDES)))
            meta[name] = m
    return meta


def load_manifest():
    names, baseline = [], None
    for line in open(MANIFEST, encoding='utf-8'):
        s = line.strip()
        if s.startswith('#'):
            m = re.match(r'#\s*baseline-commit:\s*([0-9a-f]+)', s)
            if m:
                baseline = m.group(1)
            continue
        if s:
            names.append(s)
    return names, baseline


def parse_dev_unlock():
    """Prefixes whose @READONLY is ignored in the DEV build."""
    src = open(os.path.join(REPO, DEV_UNLOCK_H), encoding='utf-8').read()
    try:
        body = src.split('xplorer_dev_unlock[] = {', 1)[1].split('};', 1)[0]
    except IndexError:
        raise SystemExit('FAIL: could not parse the unlock list from %s'
                         % DEV_UNLOCK_H)
    pre = re.findall(r'"([A-Z0-9_]+)"', body)
    if not pre:
        raise SystemExit('FAIL: unlock list in %s is empty' % DEV_UNLOCK_H)
    return pre


def load_waivers():
    """{name: reason} for sanity-check findings that are accepted, not defects."""
    if not os.path.exists(WAIVERS):
        return {}
    return {r['name'].strip(): r.get('reason', '').strip()
            for r in csv.DictReader(open(WAIVERS, encoding='utf-8'))
            if r.get('name', '').strip() and not r['name'].startswith('#')}


def load_notes():
    if not os.path.exists(NOTES):
        return {}
    return {r['name'].strip(): r.get('notes', '').strip()
            for r in csv.DictReader(open(NOTES, encoding='utf-8'))
            if r.get('name', '').strip()}


# --------------------------------------------------------------------------
# assembly
# --------------------------------------------------------------------------

FIELDS = ['name', 'group', 'default', 'read_only', 'user_visible',
          'clamp_min', 'clamp_max', 'display_name', 'description', 'units',
          'values', 'bitmask', 'doc_range_min', 'doc_range_max',
          'user_level', 'reboot_required', 'notes', 'source']


def flat_kv(v):
    if not isinstance(v, dict):
        return '' if v in (None, '') else str(v)

    def key(k):
        try:
            return (0, float(k))
        except ValueError:
            return (1, k)
    return ', '.join('%s:%s' % (k, v[k]) for k in sorted(v, key=key))


def group_of(name):
    for sep in ('_',):
        if sep in name:
            head = name.split(sep)[0]
            return re.sub(r'\d+$', '', head) or head
    return name


def build(dev=False):
    problems, notices = [], []
    print('Collecting inputs ...')
    ensure_pdef()
    defaults = parse_defaults_parm(DEFAULTS_PARM)
    clamps = parse_clamps(CLAMPS_H)
    hidden_prefixes, hidden_exact = derive_hidden()
    meta = load_pdef()
    names, baseline = load_manifest()
    notes = load_notes()
    waivers = load_waivers()

    lua = {}
    for rel, prefix in LUA_APPLETS:
        lua.update(parse_lua_params(rel, prefix))
        mirror = LUA_DEPLOY_MIRROR.get(rel)
        if mirror:
            mp = os.path.join(REPO, mirror)
            tp = os.path.join(REPO, rel)
            if os.path.exists(mp) and os.path.exists(tp):
                a = open(tp, encoding='utf-8', errors='ignore').read()
                b = open(mp, encoding='utf-8', errors='ignore').read()
                if a != b:
                    problems.append(
                        'Lua applet mirror out of sync: %s differs from the '
                        'tracked %s - the deployed script is not the documented '
                        'one' % (mirror, rel))

    print('  defaults.parm      %d params (%d @READONLY)'
          % (len(defaults), sum(1 for v in defaults.values() if v[1])))
    print('  clamp table        %d' % len(clamps))
    print('  hidden prefixes    %d  + %d individual params'
          % (len(hidden_prefixes), len(hidden_exact)))
    print('  metadata           %d params' % len(meta))
    print('  Lua applet params  %d' % len(lua))
    print('  manifest           %d rows' % len(names))
    print('  human notes        %d' % len(notes))
    print('  check waivers      %d' % len(waivers))

    def is_hidden(n):
        if n in hidden_exact:
            return True
        return any(n.startswith(p) for p in hidden_prefixes)

    unlock = parse_dev_unlock() if dev else []
    if dev:
        print('  DEV unlock         %d prefixes' % len(unlock))

    rows = []
    for n in names:
        m = meta.get(n)
        lu = lua.get(n)
        seeded = n in defaults
        dflt, ro, inline = defaults.get(n, (None, False, ''))
        cl = clamps.get(n)
        if dev:
            if ro and any(n.startswith(pfx) for pfx in unlock):
                ro = False
            cl = None          # the DEV build bypasses the clamp table entirely
        rng = (m.get('Range') or {}) if m else {}
        lrng = lu.get('range') if lu else None

        if lu:
            src = lu['source']
        elif m:
            src = 'apm.pdef.json'
        else:
            src = 'NO METADATA'
            problems.append('no metadata: %s' % n)

        note = notes.get(n, '')
        if inline:
            note = ('defaults.parm: # %s' % inline) + (' | ' + note if note else '')

        rows.append({
            'name': n,
            'group': group_of(n),
            'default': dflt if seeded else (lu['default'] if lu else None),
            'read_only': ro,
            'user_visible': not is_hidden(n),
            'clamp_min': cl[0] if cl else None,
            'clamp_max': cl[1] if cl else None,
            'display_name': (m or {}).get('DisplayName', ''),
            'description': ' '.join(((m or {}).get('Description')
                                     or (lu or {}).get('description', '')).split()),
            'units': (m or {}).get('Units', '') or ('' if not lu else ''),
            'values': flat_kv((m or {}).get('Values')),
            'bitmask': flat_kv((m or {}).get('Bitmask')),
            'doc_range_min': rng.get('low', lrng[0] if lrng else None),
            'doc_range_max': rng.get('high', lrng[1] if lrng else None),
            'user_level': (m or {}).get('User', ''),
            'reboot_required': (m or {}).get('RebootRequired', ''),
            'notes': note,
            'source': src,
        })

    # sanity: a seeded default that falls outside the parameter's own documented
    # range. Either the default is wrong or the range is - both are bugs, and for
    # Lua params the value is silently clamped at read time with no warning.
    for r in rows:
        lo, hi = r['doc_range_min'], r['doc_range_max']
        v = r['default']
        if v is None or lo in (None, '') or hi in (None, ''):
            continue
        try:
            lo, hi, v = float(lo), float(hi), float(v)
        except (TypeError, ValueError):
            continue
        if lo <= v <= hi:
            continue
        msg = ('default out of documented range: %s = %g, range %g..%g%s'
               % (r['name'], v, lo, hi,
                  ' (Lua script clamps this at read time)'
                  if 'Lua applet' in r['source'] else ''))
        if r['name'] in waivers:
            notices.append(msg + '  [waived: %s]' % waivers[r['name']])
        elif v == 0 and lo > 0:
            # Very common upstream idiom: 0 means off/disabled and sits outside
            # the documented "useful" range. Informational, not a defect.
            notices.append(msg + '  [0 = disabled idiom]')
        else:
            problems.append(msg)

    # a clamp-table window that excludes the seeded default would be scrubbed at
    # boot, silently rewriting the shipped default
    for r in rows:
        if r['clamp_min'] is None or r['default'] is None:
            continue
        if not (r['clamp_min'] <= r['default'] <= r['clamp_max']):
            problems.append(
                'seeded default outside its own clamp window (boot scrub will '
                'rewrite it): %s = %g, clamp %g..%g'
                % (r['name'], r['default'], r['clamp_min'], r['clamp_max']))

    # every board's defaults.parm must be byte-identical
    base = open(DEFAULTS_PARM, encoding='utf-8').read()
    for m in DEFAULTS_MIRRORS:
        mp = os.path.join(REPO, m)
        if not os.path.exists(mp):
            problems.append('missing defaults.parm mirror: %s' % m)
        elif open(mp, encoding='utf-8').read() != base:
            problems.append('defaults.parm mirror out of sync: %s differs from '
                            '%s' % (m, os.path.relpath(DEFAULTS_PARM, REPO)))

    # drift checks
    extra = sorted(set(defaults) - set(names))
    if extra:
        problems.append('in defaults.parm but not in the manifest: %s'
                        % ', '.join(extra))
    if baseline:
        added = params_added_since(baseline)
        unlisted = sorted(added - set(names))
        if unlisted:
            problems.append(
                'param(s) added to source since baseline %s but missing from the '
                'manifest: %s' % (baseline, ', '.join(unlisted)))

    meta_info = {
        'generated': datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC'),
        'commit': git('rev-parse', '--short', 'HEAD'),
        'branch': git('rev-parse', '--abbrev-ref', 'HEAD'),
        'describe': git('describe', '--tags', '--always', '--dirty'),
        'board': ('CubeOrangePlus-ODID-DEV (ENGINEERING - params unlocked)'
                  if dev else BOARD),
        'vehicle': VEHICLE,
        'count': len(rows),
        'readonly': sum(1 for r in rows if r['read_only']),
        'hidden': sum(1 for r in rows if not r['user_visible']),
        'clamped': sum(1 for r in rows if r['clamp_min'] is not None),
    }
    return rows, meta_info, problems, notices


def params_added_since(baseline):
    """Param names whose definitions were ADDED to the source after `baseline`."""
    diff = git('diff', '%s..HEAD' % baseline, '--unified=0', '--',
               '*.cpp', '*.h')
    out = set()
    if not diff:
        return out
    # collect added definitions, plus the group prefix is unknown here so we
    # match on suffix later; store bare names.
    for m in re.finditer(r'^\+.*?\b(?:AP_GROUPINFO|AP_GROUPINFO_FLAGS|'
                         r'AP_GROUPINFO_FRAME|AP_GROUPINFO_FLAGS_FRAME|GSCALAR|'
                         r'GSCALAR_HIDDEN|ASCALAR)\s*\(\s*"([A-Za-z0-9_]+)"',
                         diff, re.M):
        out.add(m.group(1))
    return out


# --------------------------------------------------------------------------
# emitters
# --------------------------------------------------------------------------

def fmt(v):
    if v is None or v == '':
        return ''
    if isinstance(v, bool):
        return 'True' if v else 'False'
    if isinstance(v, float) and v == int(v) and abs(v) < 1e15:
        return str(int(v))
    return str(v)


def emit_csv(rows, meta_info, path):
    with open(path, 'w', newline='', encoding='utf-8') as f:
        w = csv.writer(f)
        w.writerow(FIELDS)
        for r in rows:
            w.writerow([fmt(r[k]) for k in FIELDS])
    return path


def emit_xlsx(rows, meta_info, path):
    try:
        import openpyxl
        from openpyxl.styles import Font, PatternFill, Alignment
        from openpyxl.utils import get_column_letter
    except ImportError:
        warn('openpyxl not installed - skipping xlsx (pip install openpyxl)')
        return None
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = 'xplorer-params'
    ws.append([f.replace('_', ' ') for f in FIELDS])
    NUM = {'default', 'clamp_min', 'clamp_max', 'doc_range_min', 'doc_range_max'}
    for r in rows:
        ws.append([r[k] if k in NUM else
                   (r[k] if isinstance(r[k], bool) else fmt(r[k]))
                   for k in FIELDS])
    for c in ws[1]:
        c.font = Font(bold=True)
        c.alignment = Alignment(wrap_text=True, vertical='top')
    ws.freeze_panes = 'B2'
    ws.auto_filter.ref = 'A1:%s%d' % (get_column_letter(len(FIELDS)), ws.max_row)
    widths = {'name': 24, 'group': 10, 'display_name': 30, 'description': 80,
              'notes': 50, 'values': 32, 'bitmask': 32, 'source': 18}
    for i, f in enumerate(FIELDS, start=1):
        ws.column_dimensions[get_column_letter(i)].width = widths.get(f, 12)
    ro = PatternFill('solid', fgColor='FDE9E9')
    for row in ws.iter_rows(min_row=2):
        if row[FIELDS.index('read_only')].value is True:
            row[0].fill = ro

    info = wb.create_sheet('about')
    info.append(['Xplorer parameter disposition'])
    for k in ('generated', 'commit', 'branch', 'describe', 'board', 'vehicle',
              'count', 'readonly', 'hidden', 'clamped'):
        info.append([k, str(meta_info[k])])
    info.append([])
    info.append(['GENERATED FILE - do not hand-edit.'])
    info.append(['Regenerate', 'python Tools/xplorer/gen_param_docs.py'])
    info.column_dimensions['A'].width = 18
    info.column_dimensions['B'].width = 70
    wb.save(path)
    return path


HTML_TMPL = """<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Xplorer Parameters &mdash; __BOARD__</title>
<style>
:root{--bg:#fff;--fg:#1a1d21;--mut:#5b636e;--line:#e3e6ea;--card:#f7f8fa;
--accent:#0b6bcb;--ro:#b3261e;--roBg:#fdeceb;--hid:#7a5300;--hidBg:#fdf3d7;
--cl:#0b6b52;--clBg:#e6f4ef;--code:#f0f2f5}
@media (prefers-color-scheme:dark){:root{--bg:#14171a;--fg:#e6e9ed;--mut:#9aa4b0;
--line:#2a2f36;--card:#1b1f24;--accent:#6cb0f5;--ro:#ff8a80;--roBg:#3a1f1d;
--hid:#f0c96b;--hidBg:#38300f;--cl:#7fd7b8;--clBg:#13312a;--code:#22272d}}
:root[data-theme=dark]{--bg:#14171a;--fg:#e6e9ed;--mut:#9aa4b0;--line:#2a2f36;
--card:#1b1f24;--accent:#6cb0f5;--ro:#ff8a80;--roBg:#3a1f1d;--hid:#f0c96b;
--hidBg:#38300f;--cl:#7fd7b8;--clBg:#13312a;--code:#22272d}
:root[data-theme=light]{--bg:#fff;--fg:#1a1d21;--mut:#5b636e;--line:#e3e6ea;
--card:#f7f8fa;--accent:#0b6bcb;--ro:#b3261e;--roBg:#fdeceb;--hid:#7a5300;
--hidBg:#fdf3d7;--cl:#0b6b52;--clBg:#e6f4ef;--code:#f0f2f5}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);
font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}
.wrap{max-width:1180px;margin:0 auto;padding:28px 20px 80px}
h1{font-size:1.6rem;margin:0 0 4px;letter-spacing:-.02em}
.sub{color:var(--mut);font-size:.85rem;margin-bottom:20px}
.sub code{background:var(--code);padding:1px 5px;border-radius:4px;font-size:.95em}
.stats{display:flex;flex-wrap:wrap;gap:10px;margin-bottom:18px}
.stat{background:var(--card);border:1px solid var(--line);border-radius:9px;
padding:9px 13px;min-width:92px}
.stat b{display:block;font-size:1.28rem;line-height:1.15;letter-spacing:-.02em}
.stat span{color:var(--mut);font-size:.72rem;text-transform:uppercase;
letter-spacing:.05em}
.controls{position:sticky;top:0;background:var(--bg);padding:12px 0;
border-bottom:1px solid var(--line);z-index:5;display:flex;gap:9px;flex-wrap:wrap}
input[type=search],select{background:var(--card);color:var(--fg);
border:1px solid var(--line);border-radius:8px;padding:9px 11px;font-size:14px;
font-family:inherit}
input[type=search]{flex:1;min-width:210px}
label.ck{display:inline-flex;align-items:center;gap:5px;font-size:13px;
color:var(--mut);background:var(--card);border:1px solid var(--line);
border-radius:8px;padding:0 11px;cursor:pointer}
#count{color:var(--mut);font-size:.8rem;padding:9px 2px}
.scroll{overflow-x:auto;margin-top:2px}
table{border-collapse:collapse;width:100%;font-size:13.5px}
th{text-align:left;font-size:.7rem;text-transform:uppercase;letter-spacing:.05em;
color:var(--mut);border-bottom:1px solid var(--line);padding:9px 8px;
white-space:nowrap;font-weight:600}
td{border-bottom:1px solid var(--line);padding:9px 8px;vertical-align:top}
tr.p:hover{background:var(--card)}
.nm{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
font-weight:600;white-space:nowrap}
.nm a{color:inherit;text-decoration:none}
.nm a:hover{color:var(--accent)}
.dv{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
white-space:nowrap;text-align:right}
.tags{white-space:nowrap}
.t{display:inline-block;font-size:.64rem;font-weight:700;padding:2px 5px;
border-radius:4px;text-transform:uppercase;letter-spacing:.04em;margin-right:3px}
.t.ro{color:var(--ro);background:var(--roBg)}
.t.hd{color:var(--hid);background:var(--hidBg)}
.t.cl{color:var(--cl);background:var(--clBg)}
.dn{font-weight:600}
.ds{color:var(--mut);font-size:12.5px;margin-top:2px}
.en{margin-top:4px;font-size:12px;color:var(--mut);
font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
background:var(--code);padding:4px 6px;border-radius:5px;
display:inline-block;max-width:100%;overflow-wrap:anywhere}
.nt{margin-top:4px;font-size:12.5px;color:var(--fg);border-left:2px solid var(--accent);
padding-left:7px}
.empty{padding:40px 4px;color:var(--mut);text-align:center}
footer{margin-top:34px;padding-top:14px;border-top:1px solid var(--line);
color:var(--mut);font-size:.78rem}
@media(max-width:760px){.co{display:none}}
</style>
<div class="wrap">
<h1>Xplorer Parameters</h1>
<div class="sub">__BOARD__ &middot; __VEHICLE__ &middot; generated __GENERATED__ from
<code>__COMMIT__</code> (__BRANCH__)</div>
<div class="stats">
<div class="stat"><b>__COUNT__</b><span>Parameters</span></div>
<div class="stat"><b>__READONLY__</b><span>Read-only</span></div>
<div class="stat"><b>__HIDDEN__</b><span>Hidden</span></div>
<div class="stat"><b>__CLAMPED__</b><span>Clamped</span></div>
</div>
<div class="controls">
<input type="search" id="q" placeholder="Search name, description, notes&hellip;"
autocomplete="off">
<select id="g"><option value="">All groups</option>__GROUPS__</select>
<label class="ck"><input type="checkbox" id="fro"> Read-only</label>
<label class="ck"><input type="checkbox" id="fhd"> Hidden</label>
<label class="ck"><input type="checkbox" id="fcl"> Clamped</label>
<label class="ck"><input type="checkbox" id="fnt"> Has notes</label>
<span id="count"></span>
</div>
<div class="scroll">
<table><thead><tr>
<th>Parameter</th><th class="dv">Default</th><th>Flags</th>
<th class="co">Range</th><th>Description &amp; notes</th>
</tr></thead><tbody id="tb">__ROWS__</tbody></table>
</div>
<div class="empty" id="none" hidden>No parameters match.</div>
<footer>Generated by <code>Tools/xplorer/gen_param_docs.py</code> &mdash; do not
hand-edit. Defaults and read-only come from <code>defaults.parm</code>; hidden
from <code>AP_PARAM_FLAG_HIDDEN</code>; clamps from
<code>GCS_Param_Clamps.h</code>. __DESCRIBE__</footer>
</div>
<script>
var rows=[].slice.call(document.querySelectorAll('#tb tr.p'));
var q=document.getElementById('q'),g=document.getElementById('g'),
cnt=document.getElementById('count'),none=document.getElementById('none'),
fro=document.getElementById('fro'),fhd=document.getElementById('fhd'),
fcl=document.getElementById('fcl'),fnt=document.getElementById('fnt');
function apply(){
 var t=q.value.toLowerCase().trim(),grp=g.value,n=0;
 var kro=fro.checked,khd=fhd.checked,kcl=fcl.checked,knt=fnt.checked;
 for(var i=0;i<rows.length;i++){var r=rows[i];
  var ok=(!t||r.dataset.s.indexOf(t)>=0)&&(!grp||r.dataset.g===grp)
   &&(!kro||r.dataset.ro==='1')&&(!khd||r.dataset.hd==='1')
   &&(!kcl||r.dataset.cl==='1')&&(!knt||r.dataset.nt==='1');
  r.hidden=!ok;if(ok)n++;}
 cnt.textContent=n+' of '+rows.length;none.hidden=n>0;}
q.addEventListener('input',apply);g.addEventListener('change',apply);
[fro,fhd,fcl,fnt].forEach(function(c){c.addEventListener('change',apply)});
if(location.hash){var h=decodeURIComponent(location.hash.slice(1));
 if(h){q.value=h}}
apply();
</script>
"""


def emit_html(rows, meta_info, path):
    def esc(s):
        return (str(s).replace('&', '&amp;').replace('<', '&lt;')
                .replace('>', '&gt;').replace('"', '&quot;'))

    groups = sorted({r['group'] for r in rows})
    opts = ''.join('<option value="%s">%s</option>' % (esc(g), esc(g))
                   for g in groups)

    out = []
    for r in rows:
        tags = ''
        if r['read_only']:
            tags += '<span class="t ro">RO</span>'
        if not r['user_visible']:
            tags += '<span class="t hd">Hidden</span>'
        if r['clamp_min'] is not None:
            tags += '<span class="t cl">Clamp</span>'

        rng = ''
        if r['clamp_min'] is not None:
            rng = '%s&ndash;%s' % (fmt(r['clamp_min']), fmt(r['clamp_max']))
        elif r['doc_range_min'] not in (None, ''):
            rng = '<span style="color:var(--mut)">%s&ndash;%s</span>' % (
                fmt(r['doc_range_min']), fmt(r['doc_range_max']))
        if r['units']:
            rng += ' <span style="color:var(--mut)">%s</span>' % esc(r['units'])

        body = ''
        if r['display_name']:
            body += '<div class="dn">%s</div>' % esc(r['display_name'])
        if r['description']:
            body += '<div class="ds">%s</div>' % esc(r['description'])
        enum = r['values'] or r['bitmask']
        if enum:
            label = 'Values' if r['values'] else 'Bitmask'
            body += '<div class="en">%s: %s</div>' % (label, esc(enum))
        if r['notes']:
            body += '<div class="nt">%s</div>' % esc(r['notes'])

        srch = ' '.join([r['name'], r['display_name'], r['description'],
                         r['notes'], enum]).lower()
        out.append(
            '<tr class="p" data-s="%s" data-g="%s" data-ro="%s" data-hd="%s"'
            ' data-cl="%s" data-nt="%s">'
            '<td class="nm"><a id="%s" href="#%s">%s</a></td>'
            '<td class="dv">%s</td><td class="tags">%s</td>'
            '<td class="co dv">%s</td><td>%s</td></tr>'
            % (esc(srch), esc(r['group']), '1' if r['read_only'] else '0',
               '0' if r['user_visible'] else '1',
               '1' if r['clamp_min'] is not None else '0',
               '1' if r['notes'] else '0',
               esc(r['name']), esc(r['name']), esc(r['name']),
               fmt(r['default']) or '<span style="color:var(--mut)">&mdash;</span>',
               tags or '<span style="color:var(--mut)">&mdash;</span>',
               rng or '&mdash;', body))

    html = HTML_TMPL
    for k, v in [('__BOARD__', meta_info['board']),
                 ('__VEHICLE__', meta_info['vehicle']),
                 ('__GENERATED__', meta_info['generated']),
                 ('__COMMIT__', meta_info['commit']),
                 ('__BRANCH__', meta_info['branch']),
                 ('__DESCRIBE__', esc(meta_info['describe'])),
                 ('__COUNT__', str(meta_info['count'])),
                 ('__READONLY__', str(meta_info['readonly'])),
                 ('__HIDDEN__', str(meta_info['hidden'])),
                 ('__CLAMPED__', str(meta_info['clamped'])),
                 ('__GROUPS__', opts),
                 ('__ROWS__', '\n'.join(out))]:
        html = html.replace(k, v)
    # newline='\n' so the bytes are identical no matter which interpreter writes
    # them. Without it, Windows Python translates \n -> \r\n while Cygwin Python
    # does not, so a file written by one looks "out of date" to the other and
    # --check fails forever. build_release.sh runs under Cygwin; a developer
    # regenerating from a Windows shell does not.
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(html)
    return path


# --------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--format', default='all',
                    choices=['all', 'csv', 'xlsx', 'html'])
    ap.add_argument('--outdir', default=OUTDIR)
    ap.add_argument('--dev', action='store_true',
                    help='describe the CubeOrangePlus-ODID-DEV build instead: '
                         'applies the xplorer_dev_unlock.h list and drops the '
                         'clamp columns. Writes xplorer-params-DEV.*')
    ap.add_argument('--check', action='store_true',
                    help='regenerate into a temp dir and fail if outputs would '
                         'change or drift is detected (for CI)')
    ap.add_argument('--refresh-metadata', action='store_true',
                    help='force regeneration of apm.pdef.json')
    args = ap.parse_args()

    if args.refresh_metadata and os.path.exists(PDEF_JSON):
        os.remove(PDEF_JSON)

    rows, meta_info, problems, notices = build(dev=args.dev)

    outdir = args.outdir
    if args.check:
        import tempfile
        outdir = tempfile.mkdtemp(prefix='xplorer-params-')
    os.makedirs(outdir, exist_ok=True)
    STEM = 'xplorer-params-DEV' if args.dev else 'xplorer-params'

    written = []
    if args.format in ('all', 'csv'):
        written.append(emit_csv(rows, meta_info, os.path.join(outdir, STEM + '.csv')))
    if args.format in ('all', 'xlsx'):
        p = emit_xlsx(rows, meta_info, os.path.join(outdir, STEM + '.xlsx'))
        if p:
            written.append(p)
    if args.format in ('all', 'html'):
        written.append(emit_html(rows, meta_info, os.path.join(outdir, STEM + '.html')))

    print('\n%d parameters | %d read-only | %d hidden | %d clamped'
          % (meta_info['count'], meta_info['readonly'], meta_info['hidden'],
             meta_info['clamped']))

    if args.check:
        stale = []
        for p in written:
            live = os.path.join(args.outdir, os.path.basename(p))
            if os.path.basename(p).endswith('.xlsx'):
                continue          # xlsx bytes are not reproducible; csv covers it
            if not os.path.exists(live):
                stale.append('%s missing' % os.path.basename(p))
            elif _strip_stamp(open(live, encoding='utf-8').read()) != \
                    _strip_stamp(open(p, encoding='utf-8').read()):
                stale.append('%s out of date' % os.path.basename(p))
        for s in stale:
            problems.append(s)

    if problems:
        print('\nPROBLEMS (%d):' % len(problems), file=sys.stderr)
        for p in problems:
            print('  - %s' % p, file=sys.stderr)
        if args.check:
            print('\nRun: python Tools/xplorer/gen_param_docs.py', file=sys.stderr)
            return 1
    else:
        print('\nNo problems detected.')

    if not args.check:
        for p in written:
            print('  wrote %s' % os.path.relpath(p, REPO))
    return 0


def _strip_stamp(s):
    """Normalise output for --check comparison.

    Drops the generation timestamp so the check does not fire on time alone, and
    normalises line endings so it does not fire merely because a different
    interpreter wrote the file. build_release.sh runs under Cygwin Python (LF)
    while a developer regenerating by hand may use Windows Python (CRLF); either
    should be able to verify the other's output.
    """
    s = s.replace('\r\n', '\n').replace('\r', '\n')
    return re.sub(r'generated \d{4}-\d{2}-\d{2} \d{2}:\d{2} UTC', '', s)


if __name__ == '__main__':
    sys.exit(main())
